---
dist: xenial
language: python
python: "3.8"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:stretch-slim

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
