---

- name: CONSUL_EXPORTER | Copy Daemon script
  template:
    src: consul_exporter.service.j2
    dest: /etc/systemd/system/consul_exporter.service
    mode: 0644
  notify: restart consul_exporter
