---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint ../.
  ansible-lint ../.
platforms:
  - name: consulexporter_debian9
    groups:
      - consulexporter
    image: geerlingguy/docker-debian9-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    exposed_ports:
      - 9107/tcp
    published_ports:
      - 0.0.0.0:8853:9107/tcp
  - name: consulexporter_debian8
    groups:
      - consulexporter
    image: geerlingguy/docker-debian8-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  verifier:
    name: ansible
  
